### ISSUE TITLE
Make webpages aesthetic 

### ISSUE THREAD

**Issue by ChrisTutje** [ChrisTutje/TechwiseCommunicationsApp#18]
As a User, I like to look at shit that looks nice. I also like to be able to navigate the webpage intuitively.

**Comment by Eric-Holman** [comment]
-Added new background
-Fixed the container to be more stylish
-Adjusted the buttons for better styling
-Built on what Jaya had implemented before

**last minute Notes:**
Worked on the overall theme of the webpage, Jaya provided me the background for the webpage. So major credit to Jaya for the background and also the code. Code had some slight errors; she was definitely on the correct path. Added the change "background option"
